### PR TITLE
Add missing requirements

### PR DESCRIPTION
**Pull request by cmaumet**

### CODE REVIEW

**Comment by vsoch** [comment]
Thank you @cmaumet ! Do we want to make sure the list between requirements.txt and the setup.py are matching? See here  --> https://github.com/vsoch/nidmviewer/blob/master/setup.py#L30

**Comment by vsoch** [comment]
Are you guys at Code Rodeo now?! Hiii!! :D

**Comment by cmaumet** [comment]
Not at the Code Rodeo sadly but still doing some coding :D 

I've updated `setup.py` as suggested.

**Comment by vsoch** [comment]
It's ok, you can code from anywhere and still share the spirit! The changes look good, and I appreciate the help. Merging!

**Pull request merged**
