### PR TITLE
python3 support

### PR DESCRIPTION
**Pull request by vsoch**
This will add basic changes so the library supports python 3 - when we merge this I can continue debugging #19. @cmaumet do you want to take a peek here and see if it looks good to you? I started tesitng #19 but hit a bug because the module doesn't have python 3 support, which is embarrassing for me at this point, lol. :)

### CODE REVIEW

**Comment by cmaumet** [comment]
@vsoch: Supporting python 3 sounds great! If I am correct, we will also need compatibility with python 2 in order to run on NeuroVault?

Your proposed changes look good and run fine python 2 (locally tested) but when I try to run on my machine with python 3, I get the following error: 
```
$ nidmviewer ~/Downloads/pain_01.nidm/nidm.ttl 
Starting up the nidmviewer!
Found results matching query.
/Users/camaumet/anaconda2/envs/nidmviwer_py3/lib/python3.6/site-packages/nidmviewer-0.1.4-py3.6.egg/nidmviewer/sparql.py:30: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  return DataFrame.from_csv(result,sep=",")
Traceback (most recent call last):
  File "/Users/camaumet/anaconda2/envs/nidmviwer_py3/bin/nidmviewer", line 11, in <module>
    load_entry_point('nidmviewer==0.1.4', 'console_scripts', 'nidmviewer')()
  File "/Users/camaumet/anaconda2/envs/nidmviwer_py3/lib/python3.6/site-packages/nidmviewer-0.1.4-py3.6.egg/nidmviewer/scripts.py", line 45, in main
    port=args.port)
  File "/Users/camaumet/anaconda2/envs/nidmviwer_py3/lib/python3.6/site-packages/nidmviewer-0.1.4-py3.6.egg/nidmviewer/viewer.py", line 115, in generate
    base_image = base_copy.values()[0]
TypeError: 'dict_values' object does not support indexing
```

**Comment by vsoch** [comment]
Oh I forgot about the client! Heh, let me fix this up :)

**Comment by vsoch** [comment]
okay @cmaumet give it another go! Note that I'm creating a test folder as I do this, so it will help with #22 (and we can add with another PR) when all is said and done.

**Comment by cmaumet** [comment]
Okay! I can confirm that:
```
$ nidmviewer ~/Downloads/pain_01.nidm/nidm.ttl 
```
now runs without error on both python 3.6.4 and python 2.7.14. Thank you @vsoch! I think this is ready to merge!

**Comment by vsoch** [comment]
okay great! Merging.

**Pull request merged**
