### PR TITLE
adding license, contributors, changelog

### PR DESCRIPTION
**Pull request by vsoch**
Here is the first PR to break apart #24, it should be the easiest of the bunch as it adds only the "soft" changes:
 
  - updating the LICENSE, along with adding to the header of the associated files (this is the new convention that I have used as it's common for files to be considered in isolation)
 - better documentation and organization of README.md
 - adding a CHANGELOG to properly track updates, etc.
 - adding a CONTRIBUTORS.md for those that have contributed

There are no changes to the code. When this PR is reviewed I will work on the next.

### CODE REVIEW

**Comment by chrisgorgo** [comment]
Thanks for splitting the PRs. Not sure if I am in position to review this, but personally it LGTM

**Comment by vsoch** [comment]
Me as well, merging so I can work on the others.

**Comment by abitrolly** [comment]
BTW http://vsoch.github.io/nidmviewer/examples/ is blank in FF 61. Also would be nice to have a link to explanation of what `NIDM results` are.

**Comment by vsoch** [comment]
Yes, that's why it wasn't my recommendation to split this apart - the docs reference an example that is added in #24. We can do a separate PR to update the documentation for this - nidmviewer at face value didn't originally educate the user about what nidm results are, and I agree that it should.

**Pull request merged**
